default_language_version:
  python: python3.12


repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.2
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-ast
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: detect-private-key